version: '3.8'

services:
  youtube-downloader:
    build: .
    container_name: youtube-downloader
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DOMAIN=yt.leenf.online
      - HOST=0.0.0.0
      - PORT=8090
      - MAX_CONCURRENT_DOWNLOADS=3
      - DOWNLOAD_TIMEOUT=1800
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - youtube-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: youtube-nginx
    restart: unless-stopped
    ports:
      - "8090:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certbot/conf:/etc/letsencrypt:ro
      - ./ssl/certbot/www:/var/www/certbot:ro
    depends_on:
      - youtube-downloader
    networks:
      - youtube-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: youtube-certbot
    restart: "no"
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  youtube-net:
    driver: bridge

volumes:
  downloads:
  uploads:
  logs: